baseurl = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
hasCJKLanguage = "true"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

pygmentsUseClasses=true
pygmentsCodefences = true
pygmentsStyle = "monokai"

# disableKinds = ["taxonomy", "taxonomyTerm"]

[taxonomies]
    category = "en/categories"
    tag = "en/tags"
    ctag = "cn/ctags"

[permalinks]
    en = "en/:year/:month/:slug/"
    cn = "cn/:year/:month/:slug/"


[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Blog"
        url = "/en/"
        weight = 2
    [[menu.main]]
        name = "博客"
        url = "/cn/"
        weight = 3
    [[menu.en]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.en]]
        name = "Blog"
        url = "/en/"
        weight = 2
    [[menu.en]]
        name = "Categories"
        url = "/en/categories/"
        weight = 3
    [[menu.en]]
        name = "Tags"
        url = "/en/tags/"
        weight = 4
    [[menu.en]]
        name = "中文"
        url = "/cn/"
        weight = 5

    [[menu.cn]]
        name = "首页"
        url = "/"
        weight = 1
    [[menu.cn]]
        name = "博客"
        url = "/cn/"
        weight = 2
    [[menu.cn]]
        name = "标签"
        url = "/cn/ctags/"
        weight = 3
    [[menu.cn]]
        name = "English"
        url = "/en/"
        weight = 4


[params]
    # description = "A website built through Hugo and blogdown."
    footer = "&copy; [Fei Ye](https://yfei.page) 2018-2020 | [Github](https://github.com/fyemath)"

    # highlightjsCDN = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"
    # highlightjsLang = ["r", "yaml", "tex", "markdown"]
    # highlightjsTheme = "github"

    author = "Fei Ye"

    # [params.author]
    #     en = "Fei Ye"
    #     cn = "叶飞"


[markup.goldmark.renderer]
  unsafe = true # allows HTML inside your CommonMark content

[frontmatter]
  lastmod = [":fileModTime", "lastmod"]


# pygmentsUseClasses = true
# pygmentsStyle = "monokai"
# pygmentsCodefences = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  # hl_Lines = ""
  # lineNoStart = 1
  # lineNos = true
  # lineNumbersInTable = true
  # tabWidth = 4
  noClasses = true

# https://highlightjs.org
highlightjs = false
